export const LANGUAGES = [
  "en-US",
  "bn-BD",
  "hi-IN",
  "es-ES",
  "fr-FR",
  "de-DE",
  "it-IT",
  "pt-BR",
  "ar-SA",
  "zh-CN",
  "ja-JP",
  "ko-KR",
  "ru-RU",
  "tr-TR",
  "id-ID",
  "ms-MY",
  "th-TH",
  "vi-VN",
  "ur-PK",
  "ta-IN",
  "te-IN",
  "mr-IN",
  "nl-NL",
  "pl-PL",
  "uk-UA",
  "el-GR",
  "he-IL",
  "fa-IR",
  "sv-SE",
  "nb-NO",
  "da-DK",
  "fi-FI",
  "cs-CZ",
  "ro-RO",
  "hu-HU",
  "bg-BG",
  "hr-HR",
  "sr-RS",
  "sk-SK",
  "sl-SI",
  "lt-LT",
  "lv-LV",
  "et-EE",
  "fil-PH",
  "sw-TZ",
  "af-ZA",
  "sq-AL",
  "am-ET",
  "hy-AM",
  "az-AZ",
  "eu-ES",
  "be-BY",
  "bs-BA",
  "my-MM",
  "ca-ES",
  "ceb-PH",
  "ny-MW",
  "co-FR",
  "eo-001",
  "fy-NL",
  "gl-ES",
  "ka-GE",
  "gu-IN",
  "ht-HT",
  "ha-NG",
  "haw-US",
  "hmn-CN",
  "is-IS",
  "ig-NG",
  "ga-IE",
  "jv-ID",
  "kn-IN",
  "kk-KZ",
  "km-KH",
  "rw-RW",
  "ku-IQ",
  "ky-KG",
  "lo-LA",
  "la-VA",
  "lb-LU",
  "mk-MK",
  "mg-MG",
  "ml-IN",
  "mt-MT",
  "mi-NZ",
  "mn-MN",
  "ne-NP",
  "or-IN",
  "ps-AF",
  "pa-IN",
  "sm-WS",
  "gd-GB",
  "st-LS",
  "sn-ZW",
  "sd-PK",
  "si-LK",
  "so-SO",
  "su-ID",
  "tg-TJ",
  "uz-UZ",
  "cy-GB",
  "xh-ZA",
  "yi-IL",
  "yo-NG",
  "zu-ZA"
] as const;

export const LANGUAGE_OPTIONS = [
  { value: "en-US", label: "EN", name: "English", country: "US" },
  { value: "bn-BD", label: "BN", name: "Bangla", country: "BD" },
  { value: "hi-IN", label: "HI", name: "Hindi", country: "IN" },
  { value: "es-ES", label: "ES", name: "Spanish", country: "ES" },
  { value: "fr-FR", label: "FR", name: "French", country: "FR" },
  { value: "de-DE", label: "DE", name: "German", country: "DE" },
  { value: "it-IT", label: "IT", name: "Italian", country: "IT" },
  { value: "pt-BR", label: "PT", name: "Portuguese", country: "BR" },
  { value: "ar-SA", label: "AR", name: "Arabic", country: "SA" },
  { value: "zh-CN", label: "ZH", name: "Chinese", country: "CN" },
  { value: "ja-JP", label: "JA", name: "Japanese", country: "JP" },
  { value: "ko-KR", label: "KO", name: "Korean", country: "KR" },
  { value: "ru-RU", label: "RU", name: "Russian", country: "RU" },
  { value: "tr-TR", label: "TR", name: "Turkish", country: "TR" },
  { value: "id-ID", label: "ID", name: "Indonesian", country: "ID" },
  { value: "ms-MY", label: "MS", name: "Malay", country: "MY" },
  { value: "th-TH", label: "TH", name: "Thai", country: "TH" },
  { value: "vi-VN", label: "VI", name: "Vietnamese", country: "VN" },
  { value: "ur-PK", label: "UR", name: "Urdu", country: "PK" },
  { value: "ta-IN", label: "TA", name: "Tamil", country: "IN" },
  { value: "te-IN", label: "TE", name: "Telugu", country: "IN" },
  { value: "mr-IN", label: "MR", name: "Marathi", country: "IN" },
  { value: "nl-NL", label: "NL", name: "Dutch", country: "NL" },
  { value: "pl-PL", label: "PL", name: "Polish", country: "PL" },
  { value: "uk-UA", label: "UK", name: "Ukrainian", country: "UA" },
  { value: "el-GR", label: "EL", name: "Greek", country: "GR" },
  { value: "he-IL", label: "HE", name: "Hebrew", country: "IL" },
  { value: "fa-IR", label: "FA", name: "Persian", country: "IR" },
  { value: "sv-SE", label: "SV", name: "Swedish", country: "SE" },
  { value: "nb-NO", label: "NO", name: "Norwegian", country: "NO" },
  { value: "da-DK", label: "DA", name: "Danish", country: "DK" },
  { value: "fi-FI", label: "FI", name: "Finnish", country: "FI" },
  { value: "cs-CZ", label: "CS", name: "Czech", country: "CZ" },
  { value: "ro-RO", label: "RO", name: "Romanian", country: "RO" },
  { value: "hu-HU", label: "HU", name: "Hungarian", country: "HU" },
  { value: "bg-BG", label: "BG", name: "Bulgarian", country: "BG" },
  { value: "hr-HR", label: "HR", name: "Croatian", country: "HR" },
  { value: "sr-RS", label: "SR", name: "Serbian", country: "RS" },
  { value: "sk-SK", label: "SK", name: "Slovak", country: "SK" },
  { value: "sl-SI", label: "SL", name: "Slovenian", country: "SI" },
  { value: "lt-LT", label: "LT", name: "Lithuanian", country: "LT" },
  { value: "lv-LV", label: "LV", name: "Latvian", country: "LV" },
  { value: "et-EE", label: "ET", name: "Estonian", country: "EE" },
  { value: "fil-PH", label: "FI", name: "Filipino", country: "PH" },
  { value: "sw-TZ", label: "SW", name: "Swahili", country: "TZ" },
  { value: "af-ZA", label: "AF", name: "Afrikaans", country: "ZA" },
  { value: "sq-AL", label: "SQ", name: "Albanian", country: "AL" },
  { value: "am-ET", label: "AM", name: "Amharic", country: "ET" },
  { value: "hy-AM", label: "HY", name: "Armenian", country: "AM" },
  { value: "az-AZ", label: "AZ", name: "Azerbaijani", country: "AZ" },
  { value: "eu-ES", label: "EU", name: "Basque", country: "ES" },
  { value: "be-BY", label: "BE", name: "Belarusian", country: "BY" },
  { value: "bs-BA", label: "BS", name: "Bosnian", country: "BA" },
  { value: "my-MM", label: "MY", name: "Burmese", country: "MM" },
  { value: "ca-ES", label: "CA", name: "Catalan", country: "ES" },
  { value: "ceb-PH", label: "CE", name: "Cebuano", country: "PH" },
  { value: "ny-MW", label: "NY", name: "Chichewa", country: "MW" },
  { value: "co-FR", label: "CO", name: "Corsican", country: "FR" },
  { value: "eo-001", label: "EO", name: "Esperanto", country: "001" },
  { value: "fy-NL", label: "FY", name: "Frisian", country: "NL" },
  { value: "gl-ES", label: "GL", name: "Galician", country: "ES" },
  { value: "ka-GE", label: "KA", name: "Georgian", country: "GE" },
  { value: "gu-IN", label: "GU", name: "Gujarati", country: "IN" },
  { value: "ht-HT", label: "HT", name: "Haitian Creole", country: "HT" },
  { value: "ha-NG", label: "HA", name: "Hausa", country: "NG" },
  { value: "haw-US", label: "HA", name: "Hawaiian", country: "US" },
  { value: "hmn-CN", label: "HM", name: "Hmong", country: "CN" },
  { value: "is-IS", label: "IS", name: "Icelandic", country: "IS" },
  { value: "ig-NG", label: "IG", name: "Igbo", country: "NG" },
  { value: "ga-IE", label: "GA", name: "Irish", country: "IE" },
  { value: "jv-ID", label: "JV", name: "Javanese", country: "ID" },
  { value: "kn-IN", label: "KN", name: "Kannada", country: "IN" },
  { value: "kk-KZ", label: "KK", name: "Kazakh", country: "KZ" },
  { value: "km-KH", label: "KM", name: "Khmer", country: "KH" },
  { value: "rw-RW", label: "RW", name: "Kinyarwanda", country: "RW" },
  { value: "ku-IQ", label: "KU", name: "Kurdish", country: "IQ" },
  { value: "ky-KG", label: "KY", name: "Kyrgyz", country: "KG" },
  { value: "lo-LA", label: "LO", name: "Lao", country: "LA" },
  { value: "la-VA", label: "LA", name: "Latin", country: "VA" },
  { value: "lb-LU", label: "LB", name: "Luxembourgish", country: "LU" },
  { value: "mk-MK", label: "MK", name: "Macedonian", country: "MK" },
  { value: "mg-MG", label: "MG", name: "Malagasy", country: "MG" },
  { value: "ml-IN", label: "ML", name: "Malayalam", country: "IN" },
  { value: "mt-MT", label: "MT", name: "Maltese", country: "MT" },
  { value: "mi-NZ", label: "MI", name: "Maori", country: "NZ" },
  { value: "mn-MN", label: "MN", name: "Mongolian", country: "MN" },
  { value: "ne-NP", label: "NE", name: "Nepali", country: "NP" },
  { value: "or-IN", label: "OR", name: "Odia", country: "IN" },
  { value: "ps-AF", label: "PS", name: "Pashto", country: "AF" },
  { value: "pa-IN", label: "PA", name: "Punjabi", country: "IN" },
  { value: "sm-WS", label: "SM", name: "Samoan", country: "WS" },
  { value: "gd-GB", label: "GD", name: "Scots Gaelic", country: "GB" },
  { value: "st-LS", label: "ST", name: "Sesotho", country: "LS" },
  { value: "sn-ZW", label: "SN", name: "Shona", country: "ZW" },
  { value: "sd-PK", label: "SD", name: "Sindhi", country: "PK" },
  { value: "si-LK", label: "SI", name: "Sinhala", country: "LK" },
  { value: "so-SO", label: "SO", name: "Somali", country: "SO" },
  { value: "su-ID", label: "SU", name: "Sundanese", country: "ID" },
  { value: "tg-TJ", label: "TG", name: "Tajik", country: "TJ" },
  { value: "uz-UZ", label: "UZ", name: "Uzbek", country: "UZ" },
  { value: "cy-GB", label: "CY", name: "Welsh", country: "GB" },
  { value: "xh-ZA", label: "XH", name: "Xhosa", country: "ZA" },
  { value: "yi-IL", label: "YI", name: "Yiddish", country: "IL" },
  { value: "yo-NG", label: "YO", name: "Yoruba", country: "NG" },
  { value: "zu-ZA", label: "ZU", name: "Zulu", country: "ZA" }
] as const;

export const MODES = [
  { value: "cleanup", label: "Clean up" },
  { value: "professional", label: "Professional" },
  { value: "casual", label: "Casual" },
  { value: "shorter", label: "Shorter" },
  { value: "longer", label: "Longer" },
  { value: "bullet_points", label: "Bullet points" },
  { value: "email", label: "Email" },
  { value: "message", label: "Message" },
  { value: "translate_en", label: "Translate to English" },
  { value: "translate_bn", label: "Translate to Bangla" },
  { value: "translate_es", label: "Translate to Spanish" },
  { value: "translate_fr", label: "Translate to French" },
  { value: "translate_ar", label: "Translate to Arabic" }
] as const;

export type Mode = (typeof MODES)[number]["value"];
export type Language = (typeof LANGUAGES)[number];
